# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]

highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            keyboardAnt
tagline:          'Stuff'
url:              https://keyboardant.github.io/
#shorturl:         joshualande.com

author:
  name:           'keyboardAnt'
  url:            https://twitter.com/keyboardAnt

paginate:         1

# Custom vars
version:          0.1

github:
  repo:           github.com/keyboardAnt/keyboardAnt.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  RSS: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
